### ISSUE TITLE
Hello, no can view demo :/

### ISSUE THREAD

**Issue by dimoca** [Exeu/apai-io-demosite#1]
Hello, to upload the demo and install the composer, the page view white and do not understand that I am wrong :question: 

Install...
![Image of Yaktocat](http://i.imgur.com/Ens0JrG.png)

Configure...
![Image of Yaktocat](http://i.imgur.com/eWA0nlR.png)
![Image of Yaktocat](http://i.imgur.com/kAzl8sj.png)

And into the web but...
![Image of Yaktocat](http://i.imgur.com/2fOrnGI.png)

You me can help please? Sorry me english :sob:

**Comment by Exeu** [comment]
Please have a look on your error logs!
There you should find whats going on.

**Comment by dimoca** [comment]
[Sun Apr 05 17:00:27 2015] [error] [client x.x.x.x] PHP Fatal error:  Class 'Symfony\Component\Form\Forms' not found in /var/www/web.com/public_html/amazonito/vendor/silex/silex/src/Silex/Provider/FormServiceProvider.php on line 77

Sorry, the log error but don´t understand :mask:

**Comment by Exeu** [comment]
What do you not understand?

I mean its quite clear what the message says:
"You must either install the PHP intl extension" -> INTL Extension of PHP -> Install It! -> Maybe something like -> sudo apt-get install php5-intl can do this. http://php.net/manual/de/intl.installation.php

**Comment by dimoca** [comment]
Sorry install intl extension and now error this:

[Sun Apr 05 17:00:27 2015] [error] [client x.x.x.x] PHP Fatal error: Class 'Symfony\Component\Form\Forms' not found in /var/www/web.com/public_html/amazonito/vendor/silex/silex/src/Silex/Provider/FormServiceProvider.php on line 77

as I fix it? :/

**Comment by Exeu** [comment]
try something like: composer update in your demosite doc root ;)

**Comment by dimoca** [comment]
thank you very much !! :+1: 
![Image of Yaktocat](http://i.imgur.com/R0QeFSE.png)

**Comment by BFush** [comment]
@dimoca I am facing similar issues. Can you briefly enumerate the steps to get this running on localhost?

**Comment by dimoca** [comment]
@BFush I'm sorry I can not help you because it's been a long time and I do not remember the process.

**Comment by BFush** [comment]
@dimoca Can you tell me the framework in use?

**Comment by dimoca** [comment]
@BFush I'm sorry, but I do not remember and I can not help you. It has been a long time.
